### ISSUE TITLE
Problemas com o sistema de dicas

### ISSUE THREAD

**Issue by brunozalc** [rafaelgpaves/ep2#3]
- Em alguns casos é possível pedir uma dica indisponível, ganhar a dica, mas perder o jogo (tentattivas negativas).
- A função de imprimir dicas às vezes imprime uma dica só por ela estar indisponível, (== _False_) mesmo que ela não tenha sido solicitada.

**Comment by rafaelgpaves** [comment]
acho q isso ja foi consertado
no meu acho q foi, testa vc

**Comment by brunozalc** [comment]
Tudo certinho :)
